// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kamo_learnhub.Models;

#nullable disable

namespace kamo_learnhub.Migrations
{
    [DbContext(typeof(LearnHubContext))]
    partial class LearnHubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kamo_learnhub.Models.StudentProfile", b =>
                {
                    b.Property<int>("Student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_ID"));

                    b.Property<string>("Curriculum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Student_ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("kamo_learnhub.Models.StudentVideo", b =>
                {
                    b.Property<int>("StudentVideo_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentVideo_ID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<int>("Video_ID")
                        .HasColumnType("int");

                    b.HasKey("StudentVideo_ID");

                    b.HasIndex("Student_ID");

                    b.HasIndex("Video_ID");

                    b.ToTable("StudentVideos");
                });

            modelBuilder.Entity("kamo_learnhub.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole_ID")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.HasIndex("UserRole_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("kamo_learnhub.Models.UserRole", b =>
                {
                    b.Property<int>("UserRole_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRole_ID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRole_ID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("kamo_learnhub.Models.Video", b =>
                {
                    b.Property<int>("Video_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Video_ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGeneral")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Video_ID");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("kamo_learnhub.Models.StudentProfile", b =>
                {
                    b.HasOne("kamo_learnhub.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("kamo_learnhub.Models.StudentProfile", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kamo_learnhub.Models.StudentVideo", b =>
                {
                    b.HasOne("kamo_learnhub.Models.StudentProfile", "StudentProfile")
                        .WithMany("StudentVideos")
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kamo_learnhub.Models.Video", "Video")
                        .WithMany("StudentVideos")
                        .HasForeignKey("Video_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("kamo_learnhub.Models.User", b =>
                {
                    b.HasOne("kamo_learnhub.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRole_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("kamo_learnhub.Models.StudentProfile", b =>
                {
                    b.Navigation("StudentVideos");
                });

            modelBuilder.Entity("kamo_learnhub.Models.User", b =>
                {
                    b.Navigation("StudentProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("kamo_learnhub.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("kamo_learnhub.Models.Video", b =>
                {
                    b.Navigation("StudentVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
